### ISSUE TITLE
Q1 test tuesday material

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#1107]
## Acceptances

- Keep unit test coverage over 90% in the client-js project
- Increase e2e test coverage with 50% on the admin-ui (current number of tests 60) -> 90 tests
- Increase relation data provider and sql provider coverage with 30%
- Discover at least 20 bugs and open issues

- [ ] client e2e tests
- [x] local snaas environment
- [x] staging snaas environment
- [x] integration test platform
- [ ] integration tests
