### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-client#12]
We should talk about the standalone Search UI component for React during the next refinement.
 - [x] Expectations / feature list for 1.0
   - [x] Components
     - [ ] ~autocomplete search~
     - [ ] ~hit list~
     - [x] advanced search view, field controls for search
     - [x] custom controls for field types

   - [x] Built-in examples - decide later
   - [ ] ~~Showcase application (?) - decide later~~
   - [x] "Saved Queries". Private queries for the while. Add save button to hit list + text field to name it. + Run/Rename/Delete. Do not modify saved query yet.
 - [x] Integration to DMS
   - [x] Additional custom components (e.g. field controls for "Shared with")
   - [x] Connection with the Content List
 - [x] Create Epic / Tasks

![image](https://user-images.githubusercontent.com/16716099/45941216-66e8a380-bfdd-11e8-930f-887cd993ad82.png)

![image](https://user-images.githubusercontent.com/16716099/45941231-736cfc00-bfdd-11e8-80e4-f4c9dbfe3261.png)

![image](https://user-images.githubusercontent.com/16716099/45941251-8bdd1680-bfdd-11e8-8fb4-53e43732f2f9.png)
