### ISSUE TITLE
[FEATURE] TODO example app redesign

### ISSUE THREAD

**Issue by huszerlbence** [SenseNet/sn-client#1218]
# 🙋 Feature Request

I would like to have a redesigned version of the current todo app.

## 📦 Package / Application

https://github.com/SenseNet/sn-client/tree/master/examples/sn-react-tasklist

## 🚦Acceptance criteria
- [x] sn logo from the background should go (delete)
- [x] header should be generic example apps header (https://github.com/SenseNet/sn-client/issues/1173)
  - [x] top right context menu should be hidden

## 🖥 Color guide (design is for extended version, please do not imlplement it now)

main color: #019592
highlight color: #C8FFF4
![image](https://user-images.githubusercontent.com/19875603/109291315-1ec2b080-7829-11eb-935f-9add9104cfe5.png)
