### ISSUE TITLE
Field controls

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-client#20]
- [ ] Update Material
 - [ ] Dynamic schema loading
 - [ ] Writing/fixing Tests

---

 - [ ] Localization
 - [ ] Grouping, ordering
 - [ ] Research on complex field controls (e.g. autocomplete, reference field)
