### ISSUE TITLE
[admin-ui] Command palette revamp

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-client#424]
- [ ] simple text search (without cql)
- [ ] it would be nice to use case insensitive queries (e.g. InTree, intree and inTree) 
- [ ] requests are send on all the keyup events, so please add a delay because there're tons of errors on the console because of half typed, invalid queries
- [ ] after opening the search result page and clickin back to the search box, only the part of the previously executed query is shown in the box
- [ ] after choosing the 'search' menu, there should be a search box just as on the search results page
- [ ] rethink the 'saved queries' feature
