### ISSUE TITLE
Upgrade and refactor storybook

### ISSUE THREAD

**Issue by zoltanbedi** [SenseNet/sn-client#594]
We should upgrade and refactor storybook a bit.

## The problem
With the new version of storybook some of the addons we use got deprecated. This makes upgrading and maintaining the stories not easy.

## Tasks

- [ ] Use the [migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) to upgrade to storybook 6
- [ ] Use the [create react app preset](https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app) for bundling
- [ ] Remove dependencies that are not needed anymore 
- [ ] Refactor the stories to either [CSF](https://storybook.js.org/docs/formats/component-story-format/) or [MDX](https://storybook.js.org/docs/formats/mdx-syntax/)
- [ ] Uncomment sn-react-component-docs in `examples/tsconfig.json`

### Tasks to be decided
- [ ] Move stories to sources (this would cause adding storybook to root, adding stories next to sources, excluding stories from package builds)

**Comment by zoltanbedi** [comment]
Looks like storybook is already version 6.
