### ISSUE TITLE
Admin UI - Alpha V2

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-client#71]
# Alpha V2

 - [x] [Localization](https://github.com/sensenet/sn-client/issues/145)
 - [x] [Content editing improvements](https://github.com/SenseNet/sn-client/issues/162)
 - [ ] fixes is @sensenet/controls-react - e.g. User Edit form with default schema
fallback control?
 - [ ] TBD
    - [ ] Monaco editor on mobile - editing doesn't work on touch devices. Look for alternative? Use a 
    - [x] Improve error boundaries - feedback tool?
 - [ ] Generic improvements (refactor, code conventions, etc...)
    - [ ] Extract ContentListPanel keyboard handler - move to ContentList component(?)
    - [ ] Move default Document Viewer settings into the DocViewer component
    - [ ] Breadcrumbs component to generic - move content-specific stuff to ContentBreadcrumb
    - [ ] Extract complex (>2field) inline props to interfaces
 - [ ] CommandPalette improvements
   - [ ] Check if can be moved from Redux to hooks
   - [x] Custom callback on activate (instead of triggering a route change)
   - [ ] Provider for context menu actions on current content
   - [ ] Provider for custom OData actions and functions on current content
   - [x] Provider for navigation entries (Go to e.g. Personal Settings, Dashboard, etc...)
 - [x] Content operations improvements with Content Picker
    - [x] Move content (from context menu)
    - [x] Copy content (from context menu)
 - [ ] New main routes
    - [x] Search & saved queries
    - [x] Version info
    - [x] Setup (settings)
    - [ ] Dashboard (Needs UX)
 - [x] Notifications
    - [x] Upload progress info
    - [x] Info about failed requests / Event log

**Comment by gallayl** [comment]
# Alpha V1 Progress

## Done
 - [x] Update layout
   - [x] Add setting to swipeable temporary / modal drawer, update mobile defaults
   - [x] Move avatar / user info / personal settings editor to drawer
 - [x] Create / Upload content
   - [x] Add FAB
   - [x] Drawer for selecting type + Upload
   - [x] Upload on file drop
   - [x] New content modal
 - [x] Change repository
   - [x] Individual session management
   - [x] Repository switcher component
 - [x] "More" actions
   - [x] Content info
   - [x] Delete
   - [x] Edit properties
---
## Next steps
 - [ ] Localization
 - [ ] Extract default Document Viewer settings
 - [ ] fixes is @sensenet/controls-react
 - [ ] monaco on mobile - alternative? fallback?
 - [ ] EditContent - Move from Redux to hooks
 - [ ] Clean up AuthorizedRoute(s)
 - [ ] Breadcrumbs component to generic
 - [ ] Extract Props from to interfaces
 - [ ] Update AllowedChildTypes in Add view
 - [ ] CommandPalette improvements
   - [ ] Check if can be moved from Redux to hooks
   - [ ] Provider for context menu actions on current content
   - [ ] Provider for navigation entries (Go to e.g. Personal Settings, Dashboard, etc...)
 - [ ] Wire Content Picker
    - [ ] Move content (from context menu)
    - [ ] Copy content (from context menu)
 - [ ] Dirty form checking (on edit properties + edit binary)
 - [ ] Search & saved queries
 - [ ] Version info
 - [ ] Setup (settings, needs UX)
 - [ ] Dashboard
 - [ ] Upload progress info
 - [ ] Info about failed requests / Event log
 - [ ] Improve error boundaries - feedback tool?
 - [ ] Extract ContentListPanel keyboard handler - move to ContentList component(?)

**Comment by gallayl** [comment]
# Alpha V2

 - [x] [Localization](https://github.com/sensenet/sn-client/issues/145)
 - [ ] Move default Document Viewer settings into the DocViewer component
 - [ ] fixes is @sensenet/controls-react - e.g. User Edit form with default schema
fallback control?
 - [ ] TBD
    - [ ] Monaco editor on mobile - editing doesn't work on touch devices. Look for alternative? Use a 
    - [ ] Improve error boundaries - feedback tool?
    - [ ] Extract ContentListPanel keyboard handler - move to ContentList component(?)
 - [ ] Generic (code conventions, refactorings, etc...
    - [ ] Extract Props from to interfaces
 - [ ] Content editing improvements
    - [ ] EditContent - Move from Redux to hooks
    - [ ] Update AllowedChildTypes in Add view - Use the new API from client-core
    - [ ] Save / Cancel functionality for binary views
    - [ ] Dirty form checking
    - [ ] Clean up AuthorizedRoute(s)
    - [ ] Breadcrumbs component to generic - Remove content-specific stuff
 - [ ] CommandPalette improvements
   - [ ] Check if can be moved from Redux to hooks
   - [ ] Custom callback on activate (instead of triggering a route change)
   - [ ] Provider for context menu actions on current content
   - [ ] Provider for navigation entries (Go to e.g. Personal Settings, Dashboard, etc...)
 - [ ] Content operations improvements with Content Picker
    - [ ] Move content (from context menu)
    - [ ] Copy content (from context menu)
 - [ ] New main routes
    - [ ] Search & saved queries
    - [ ] Version info
    - [ ] Setup (settings, needs UX)
    - [ ] Dashboard
 - [ ] Notifications
    - [ ] Upload progress info
    - [ ] Info about failed requests / Event log
