### ISSUE TITLE
Implement JWT in our example todo apps

### ISSUE THREAD

**Issue by borsi** [SenseNet/sn-client#8]
# App checklist

- [x] react example todo app
- [ ] vue.js example todo app
- [ ] angular (dani's) example todo app
- [ ] angular2 example todo app
- [ ] aurelia (bedizoli's) example todo app

**Comment by gallayl** [comment]
Issue is out of date.
